// Copyright (c) Elliot Technologies, Inc.
// SPDX-License-Identifier: BUSL-1.1

use circuit::block_constraints::{BlockCircuit, BlockTarget, Circuit as _};
use circuit::block_pre_execution_constraints::{
    BlockPreExecutionCircuit, BlockPreExecutionTarget, Circuit as _,
};
use circuit::block_tx_chain_constraints::{BlockTxChainCircuit, BlockTxChainTarget, Circuit as _};
use circuit::block_tx_constraints::{BlockTxCircuit, BlockTxTarget, Circuit as _};
use circuit::types::config::{C, CIRCUIT_CONFIG, D, F};
use circuit::types::constants::{TX_HEAVY, TX_LIGHT};
use plonky2::plonk::circuit_data::CircuitData;
use plonky2::plonk::proof::ProofWithPublicInputs;

pub type Proof = ProofWithPublicInputs<F, C, D>;

pub const CHAIN_ID: u32 = 304;
pub const HEAVY_TX_PER_PROOF: usize = 4;
pub const HEAVY_TX_MODE: u8 = TX_HEAVY;
pub const LIGHT_TX_PER_PROOF: usize = 10;
pub const LIGHT_TX_MODE: u8 = TX_LIGHT;
pub const ON_CHAIN_OPERATIONS_LIMIT: usize = 1;
pub const PUBLIC_HEAVY_TX_COUNT: usize = 10;
pub const PUBLIC_LIGHT_TX_COUNT: usize = 490;
pub const PROVER_THREAD_STACK_BYTES: usize = 64 * 1024 * 1024;

/// Compact circuit caches pregenerated by `build.rs`. Loading one is a small
/// fraction of rebuilding the circuit with `CircuitBuilder::build`.
pub mod cache_bytes {
    pub const HEAVY_TX: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/heavy_tx.bin"));
    pub const LIGHT_TX: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/light_tx.bin"));
    pub const PRE: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/pre.bin"));
    pub const HEAVY_CHAIN: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/heavy_chain.bin"));
    pub const LIGHT_CHAIN: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/light_chain.bin"));
    pub const BLOCK: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/block.bin"));
}

fn load_cached(label: &str, bytes: &[u8]) -> CircuitData<F, C, D> {
    circuit::circuit_cache::circuit_data_from_compact_bytes(bytes)
        .unwrap_or_else(|error| panic!("embedded {label} circuit cache is invalid: {error:?}"))
}

/// Deserializes the embedded dummy chain proof for a transaction mode. Cheap
/// enough to call wherever needed; never blocks on the circuit loader.
pub fn embedded_dummy_proof(tx_mode: u8) -> Proof {
    let proof_bytes: &[u8] = match tx_mode {
        TX_HEAVY => include_bytes!("../dummy-heavy-chain-proof.bin"),
        TX_LIGHT => include_bytes!("../dummy-light-chain-proof.bin"),
        _ => panic!("unsupported block transaction mode {tx_mode}"),
    };
    bincode::deserialize(proof_bytes).expect("embedded chain dummy proof is invalid")
}

/// A value produced by the background circuit loader. `get` blocks until the
/// loader publishes it; every stage is published in proving order, so in
/// practice the prover only ever waits during startup pathologies.
pub struct Staged<T> {
    cell: std::sync::OnceLock<T>,
    ready: std::sync::Mutex<std::sync::mpsc::Receiver<T>>,
}

impl<T> Staged<T> {
    fn new(ready: std::sync::mpsc::Receiver<T>) -> Self {
        Self {
            cell: std::sync::OnceLock::new(),
            ready: std::sync::Mutex::new(ready),
        }
    }

    pub fn get(&self) -> &T {
        if let Some(value) = self.cell.get() {
            return value;
        }
        let receiver = self.ready.lock().expect("stage receiver lock poisoned");
        // A second caller may have populated the cell while this one waited
        // for the lock.
        if let Some(value) = self.cell.get() {
            return value;
        }
        let value = receiver
            .recv()
            .expect("circuit loader stage never published");
        self.cell.get_or_init(|| value)
    }
}

/// The transaction-path circuits, ready shortly after construction.
pub struct TxStage {
    pub heavy_target: BlockTxTarget,
    pub heavy_data: std::sync::Arc<CircuitData<F, C, D>>,
    pub light_target: BlockTxTarget,
    pub light_data: std::sync::Arc<CircuitData<F, C, D>>,
}

/// The cyclic chain circuits.
pub struct ChainStage {
    pub heavy_target: BlockTxChainTarget,
    pub heavy_data: std::sync::Arc<CircuitData<F, C, D>>,
    pub light_target: BlockTxChainTarget,
    pub light_data: std::sync::Arc<CircuitData<F, C, D>>,
}

/// The final block circuit, needed only for the last proof.
pub struct BlockStage {
    pub target: BlockTarget,
    pub data: CircuitData<F, C, D>,
}

pub struct Circuits {
    pub pre_target: BlockPreExecutionTarget,
    pub pre_data: std::sync::Arc<CircuitData<F, C, D>>,
    tx: Staged<TxStage>,
    chains: Staged<ChainStage>,
    block: Staged<BlockStage>,
}

impl Circuits {
    /// Loads the pre-execution circuit synchronously (it is needed first) and
    /// spawns a background loader that publishes the transaction, chain, and
    /// block stages in proving order. Every `CircuitData` comes from the
    /// compile-time cache; only the target-producing circuit definitions run,
    /// and all of it overlaps proving.
    pub fn new() -> Self {
        let (pre_target, pre_data) = rayon::join(
            || BlockPreExecutionCircuit::define(CIRCUIT_CONFIG).target,
            || std::sync::Arc::new(load_cached("pre", cache_bytes::PRE)),
        );

        let (tx_sender, tx_receiver) = std::sync::mpsc::sync_channel(1);
        let (chain_sender, chain_receiver) = std::sync::mpsc::sync_channel(1);
        let (block_sender, block_receiver) = std::sync::mpsc::sync_channel(1);

        let pre_data_for_block = pre_data.clone();
        std::thread::Builder::new()
            .name("circuit-loader".into())
            .stack_size(PROVER_THREAD_STACK_BYTES)
            .spawn(move || {
                use std::sync::Arc;

                // The block cache is the largest load; start it immediately so
                // it overlaps every other stage.
                let (block_data_sender, block_data_receiver) = std::sync::mpsc::sync_channel(1);
                rayon::spawn(move || {
                    let _ = block_data_sender.send(load_cached("block", cache_bytes::BLOCK));
                });

                // Transaction stage: two cache loads and two defines, all
                // independent. Published as soon as they finish; the loader
                // keeps Arc clones for the downstream defines.
                let ((heavy_data, light_data), (heavy_target, light_target)) = rayon::join(
                    || {
                        rayon::join(
                            || Arc::new(load_cached("heavy_tx", cache_bytes::HEAVY_TX)),
                            || Arc::new(load_cached("light_tx", cache_bytes::LIGHT_TX)),
                        )
                    },
                    || {
                        rayon::join(
                            || {
                                BlockTxCircuit::define(
                                    CIRCUIT_CONFIG,
                                    HEAVY_TX_PER_PROOF,
                                    CHAIN_ID,
                                    HEAVY_TX_MODE,
                                )
                                .target
                            },
                            || {
                                BlockTxCircuit::define(
                                    CIRCUIT_CONFIG,
                                    LIGHT_TX_PER_PROOF,
                                    CHAIN_ID,
                                    LIGHT_TX_MODE,
                                )
                                .target
                            },
                        )
                    },
                );
                let (heavy_tx_data, light_tx_data) = (heavy_data.clone(), light_data.clone());
                tx_sender
                    .send(TxStage {
                        heavy_target,
                        heavy_data,
                        light_target,
                        light_data,
                    })
                    .expect("transaction stage receiver dropped");

                // Chain stage: defines consume the tx data the loader kept.
                let ((heavy_chain_target, light_chain_target), (heavy_chain_data, light_chain_data)) =
                    rayon::join(
                        || {
                            rayon::join(
                                || {
                                    BlockTxChainCircuit::define(
                                        CIRCUIT_CONFIG,
                                        &heavy_tx_data,
                                        ON_CHAIN_OPERATIONS_LIMIT,
                                    )
                                    .target
                                },
                                || {
                                    BlockTxChainCircuit::define(
                                        CIRCUIT_CONFIG,
                                        &light_tx_data,
                                        ON_CHAIN_OPERATIONS_LIMIT,
                                    )
                                    .target
                                },
                            )
                        },
                        || {
                            rayon::join(
                                || Arc::new(load_cached("heavy_chain", cache_bytes::HEAVY_CHAIN)),
                                || Arc::new(load_cached("light_chain", cache_bytes::LIGHT_CHAIN)),
                            )
                        },
                    );
                let (heavy_chain_for_block, light_chain_for_block) =
                    (heavy_chain_data.clone(), light_chain_data.clone());
                chain_sender
                    .send(ChainStage {
                        heavy_target: heavy_chain_target,
                        heavy_data: heavy_chain_data,
                        light_target: light_chain_target,
                        light_data: light_chain_data,
                    })
                    .expect("chain stage receiver dropped");

                // Block stage: the define consumes pre and chain data; the
                // cache load has been running since loader start.
                let block_target = BlockCircuit::define(
                    CIRCUIT_CONFIG,
                    &pre_data_for_block,
                    &light_chain_for_block,
                    &heavy_chain_for_block,
                    ON_CHAIN_OPERATIONS_LIMIT,
                )
                .target;
                let block_data = block_data_receiver
                    .recv()
                    .expect("block cache load never finished");
                block_sender
                    .send(BlockStage {
                        target: block_target,
                        data: block_data,
                    })
                    .expect("block stage receiver dropped");
            })
            .expect("circuit loader thread must start");

        Self {
            pre_target,
            pre_data,
            tx: Staged::new(tx_receiver),
            chains: Staged::new(chain_receiver),
            block: Staged::new(block_receiver),
        }
    }

    pub fn tx(&self) -> &TxStage {
        self.tx.get()
    }

    pub fn chains(&self) -> &ChainStage {
        self.chains.get()
    }

    pub fn block(&self) -> &BlockStage {
        self.block.get()
    }
}

#[cfg(test)]
mod tests {
    use circuit::types::constants::{TX_HEAVY, TX_LIGHT};

    use super::*;

    #[test]
    fn production_mixed_circuit_parameters_are_fixed() {
        assert_eq!(CHAIN_ID, 304);
        assert_eq!(HEAVY_TX_PER_PROOF, 4);
        assert_eq!(HEAVY_TX_MODE, TX_HEAVY);
        assert_eq!(LIGHT_TX_PER_PROOF, 10);
        assert_eq!(LIGHT_TX_MODE, TX_LIGHT);
        assert_eq!(ON_CHAIN_OPERATIONS_LIMIT, 1);
    }

    #[test]
    fn embedded_chain_dummy_proofs_deserialize() {
        let _: Proof = bincode::deserialize(include_bytes!("../dummy-heavy-chain-proof.bin"))
            .expect("embedded heavy dummy proof is invalid");
        let _: Proof = bincode::deserialize(include_bytes!("../dummy-light-chain-proof.bin"))
            .expect("embedded light dummy proof is invalid");
    }
}
