// Copyright (c) Elliot Technologies, Inc.
// SPDX-License-Identifier: BUSL-1.1

use circuit::block_constraints::{BlockCircuit, BlockTarget, Circuit as _};
use circuit::block_pre_execution_constraints::{
    BlockPreExecutionCircuit, BlockPreExecutionTarget, Circuit as _,
};
use circuit::block_tx_chain_constraints::{BlockTxChainCircuit, BlockTxChainTarget, Circuit as _};
use circuit::block_tx_constraints::{BlockTxCircuit, BlockTxTarget, Circuit as _};
use circuit::types::config::{C, CIRCUIT_CONFIG, D, F};
use circuit::types::constants::{TX_HEAVY, TX_LIGHT};
use plonky2::plonk::circuit_data::CircuitData;
use plonky2::plonk::proof::ProofWithPublicInputs;

pub type Proof = ProofWithPublicInputs<F, C, D>;

/// Compact circuit caches pregenerated by `build.rs`, zstd-compressed to keep
/// the worker binary under the harness's 512 MiB staged-artifact cap. Loading
/// one recomputes only the LDE/Merkle commitment, sigma transpose, subgroup,
/// and FFT root table — a small fraction of rebuilding the circuit with
/// `CircuitBuilder::build`.
pub mod cache_bytes {
    pub const HEAVY_TX: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/heavy_tx.bin.zst"));
    pub const LIGHT_TX: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/light_tx.bin.zst"));
    pub const PRE: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/pre.bin.zst"));
    pub const HEAVY_CHAIN: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/heavy_chain.bin.zst"));
    pub const LIGHT_CHAIN: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/light_chain.bin.zst"));
    pub const RECURSION_COMMON: &[u8] =
        include_bytes!(concat!(env!("OUT_DIR"), "/recursion_common.bin.zst"));
}

/// Coarse progress marker for the stall watchdog in `bin/prove.rs`. Written at
/// phase boundaries; if the watchdog fires, the phase determines the worker's
/// time of death, the one channel the trusted wrapper cannot collapse.
pub static WORKER_PHASE: std::sync::atomic::AtomicU8 = std::sync::atomic::AtomicU8::new(44);

pub fn set_worker_phase(phase: u8) {
    WORKER_PHASE.store(phase, std::sync::atomic::Ordering::Relaxed);
}

/// Touches every page of the embedded cache payloads sequentially, before any
/// deserialization, so a stall caused by faulting the binary's data pages is
/// attributable to its own watchdog phase (46) rather than to circuit
/// loading. The checksum keeps the reads from being optimized away; the sink
/// makes the value observable.
pub fn warm_embedded_caches() {
    set_worker_phase(46);
    let mut checksum = 0u64;
    for bytes in [
        cache_bytes::HEAVY_TX,
        cache_bytes::LIGHT_TX,
        cache_bytes::PRE,
        cache_bytes::HEAVY_CHAIN,
        cache_bytes::LIGHT_CHAIN,
        cache_bytes::RECURSION_COMMON,
    ] {
        for chunk in bytes.chunks(16 * 1024) {
            checksum = checksum.wrapping_add(chunk[0] as u64).rotate_left(1);
        }
    }
    std::hint::black_box(checksum);
}

/// Returns an embedded cache's payload: a u64 LE length prefix followed by
/// the raw bytes, borrowed zero-copy from the binary image.
pub fn cache_payload<'a>(label: &str, bytes: &'a [u8]) -> &'a [u8] {
    let (len, payload) = bytes.split_at(8);
    let raw_len = u64::from_le_bytes(len.try_into().expect("cache length prefix")) as usize;
    assert_eq!(
        payload.len(),
        raw_len,
        "embedded {label} circuit cache is truncated"
    );
    payload
}

pub(crate) fn load_cached(label: &str, bytes: &[u8]) -> CircuitData<F, C, D> {
    let raw = cache_payload(label, bytes);
    circuit::circuit_cache::circuit_data_from_compact_bytes(raw)
        .unwrap_or_else(|error| panic!("embedded {label} circuit cache is invalid: {error:?}"))
}

/// Installs the embedded recursion common data so the first chain define skips
/// the three-stage throwaway build. Idempotent; must run before chain defines.
fn install_embedded_recursion_common_data() {
    let raw = cache_payload("recursion_common", cache_bytes::RECURSION_COMMON);
    let common = circuit::circuit_cache::recursion_common_from_bytes(raw)
        .expect("embedded recursion common data is invalid");
    circuit::block_tx_chain_constraints::install_recursion_common_data(common);
}

pub const CHAIN_ID: u32 = 304;
pub const HEAVY_TX_PER_PROOF: usize = 4;
pub const HEAVY_TX_MODE: u8 = TX_HEAVY;
pub const LIGHT_TX_PER_PROOF: usize = 10;
pub const LIGHT_TX_MODE: u8 = TX_LIGHT;
pub const ON_CHAIN_OPERATIONS_LIMIT: usize = 1;
pub const PUBLIC_HEAVY_TX_COUNT: usize = 10;
pub const PUBLIC_LIGHT_TX_COUNT: usize = 490;
pub const PROVER_THREAD_STACK_BYTES: usize = 64 * 1024 * 1024;

pub struct Circuits {
    pub heavy_tx_target: BlockTxTarget,
    pub heavy_tx_data: CircuitData<F, C, D>,
    pub light_tx_target: BlockTxTarget,
    pub light_tx_data: CircuitData<F, C, D>,
    pub pre_target: BlockPreExecutionTarget,
    pub pre_data: CircuitData<F, C, D>,
    pub heavy_chain_target: BlockTxChainTarget,
    pub heavy_chain_data: CircuitData<F, C, D>,
    pub light_chain_target: BlockTxChainTarget,
    pub light_chain_data: CircuitData<F, C, D>,
    pub dummy_heavy_proof: Proof,
    pub dummy_light_proof: Proof,
}

pub(crate) struct PathCircuits {
    pub(crate) tx_target: BlockTxTarget,
    pub(crate) tx_data: CircuitData<F, C, D>,
    pub(crate) chain_target: BlockTxChainTarget,
    pub(crate) chain_data: CircuitData<F, C, D>,
    pub(crate) dummy_proof: Proof,
}

impl PathCircuits {
    pub(crate) fn new(
        tx_per_proof: usize,
        tx_mode: u8,
        tx_data: CircuitData<F, C, D>,
        chain_data: CircuitData<F, C, D>,
    ) -> Self {
        let (tx_target, chain_target) = rayon::join(
            || BlockTxCircuit::define(CIRCUIT_CONFIG, tx_per_proof, CHAIN_ID, tx_mode).target,
            || {
                BlockTxChainCircuit::define(CIRCUIT_CONFIG, &tx_data, ON_CHAIN_OPERATIONS_LIMIT)
                    .target
            },
        );

        let proof_bytes: &[u8] = match tx_mode {
            TX_HEAVY => include_bytes!("../dummy-heavy-chain-proof.bin"),
            TX_LIGHT => include_bytes!("../dummy-light-chain-proof.bin"),
            _ => panic!("unsupported block transaction mode {tx_mode}"),
        };
        let dummy_proof =
            bincode::deserialize(proof_bytes).expect("embedded chain dummy proof is invalid");

        Self {
            tx_target,
            tx_data,
            chain_target,
            chain_data,
            dummy_proof,
        }
    }
}

impl Circuits {
    pub fn new() -> Self {
        // The chain defines below read the recursion common-data cache; seed
        // it from the embedded bytes before any of them can run.
        install_embedded_recursion_common_data();
        // Cache loads run strictly sequentially so at most one decompressed
        // payload and one LDE/Merkle reconstruction is live at a time,
        // keeping the worker's transient memory peak near the baseline
        // build's. The internally parallel FFT/Merkle work still uses every
        // core; only the cross-circuit overlap is removed.
        let pre_data = load_cached("pre", cache_bytes::PRE);
        let heavy_tx_data = load_cached("heavy_tx", cache_bytes::HEAVY_TX);
        let heavy_chain_data = load_cached("heavy_chain", cache_bytes::HEAVY_CHAIN);
        let light_tx_data = load_cached("light_tx", cache_bytes::LIGHT_TX);
        let light_chain_data = load_cached("light_chain", cache_bytes::LIGHT_CHAIN);
        let (pre_target, (heavy, light)) = rayon::join(
            || BlockPreExecutionCircuit::define(CIRCUIT_CONFIG).target,
            || {
                rayon::join(
                    || {
                        PathCircuits::new(
                            HEAVY_TX_PER_PROOF,
                            HEAVY_TX_MODE,
                            heavy_tx_data,
                            heavy_chain_data,
                        )
                    },
                    || {
                        PathCircuits::new(
                            LIGHT_TX_PER_PROOF,
                            LIGHT_TX_MODE,
                            light_tx_data,
                            light_chain_data,
                        )
                    },
                )
            },
        );
        Self {
            heavy_tx_target: heavy.tx_target,
            heavy_tx_data: heavy.tx_data,
            light_tx_target: light.tx_target,
            light_tx_data: light.tx_data,
            pre_target,
            pre_data,
            heavy_chain_target: heavy.chain_target,
            heavy_chain_data: heavy.chain_data,
            light_chain_target: light.chain_target,
            light_chain_data: light.chain_data,
            dummy_heavy_proof: heavy.dummy_proof,
            dummy_light_proof: light.dummy_proof,
        }
    }

    /// Builds the final block circuit, which depends on the pre-execution and
    /// both chain circuits but is only needed for the final proof. Callers run
    /// this concurrently with transaction/chain proving.
    pub fn build_block_circuit(&self) -> (BlockTarget, CircuitData<F, C, D>) {
        let block = BlockCircuit::define(
            CIRCUIT_CONFIG,
            &self.pre_data,
            &self.light_chain_data,
            &self.heavy_chain_data,
            ON_CHAIN_OPERATIONS_LIMIT,
        );
        (block.target, block.builder.build::<C>())
    }
}

#[cfg(test)]
mod tests {
    use circuit::types::constants::{TX_HEAVY, TX_LIGHT};

    use super::*;

    #[test]
    fn production_mixed_circuit_parameters_are_fixed() {
        assert_eq!(CHAIN_ID, 304);
        assert_eq!(HEAVY_TX_PER_PROOF, 4);
        assert_eq!(HEAVY_TX_MODE, TX_HEAVY);
        assert_eq!(LIGHT_TX_PER_PROOF, 10);
        assert_eq!(LIGHT_TX_MODE, TX_LIGHT);
        assert_eq!(ON_CHAIN_OPERATIONS_LIMIT, 1);
    }

    #[test]
    fn embedded_chain_dummy_proofs_deserialize() {
        let _: Proof = bincode::deserialize(include_bytes!("../dummy-heavy-chain-proof.bin"))
            .expect("embedded heavy dummy proof is invalid");
        let _: Proof = bincode::deserialize(include_bytes!("../dummy-light-chain-proof.bin"))
            .expect("embedded light dummy proof is invalid");
    }
}
